In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [2]:
data = pd.DataFrame(pd.read_csv("C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\var-project\\data\\prices.csv"))
data = data.set_index('Date')
data.tail()

,HDFCBANK.NS,INFY.NS,ITC.NS,LT.NS,RELIANCE.NS,SUNPHARMA.NS
Date,,,,,,
2026-09-14,708.250000,1037.699951,259.850006,3930.699951,1257.500000,1840.000000
2026-09-15,716.549988,1077.000000,258.000000,3850.699951,1235.300049,1835.000000
2026-09-16,721.500000,1060.000000,264.149994,3807.699951,1240.000000,1853.500000
2026-09-17,713.000000,1058.599976,266.200012,3836.199951,1243.900024,1867.300049
2026-09-18,731.000000,1051.400024,262.299988,3885.000000,1226.400024,1837.300049

In [3]:
returns = data.pct_change().dropna()
returns.tail()

,HDFCBANK.NS,INFY.NS,ITC.NS,LT.NS,RELIANCE.NS,SUNPHARMA.NS
Date,,,,,,
2026-09-14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2026-09-15,0.011719,0.037872,-0.007120,-0.020353,-0.017654,-0.002717
2026-09-16,0.006908,-0.015785,0.023837,-0.011167,0.003805,0.010082
2026-09-17,-0.011781,-0.001321,0.007761,0.007485,0.003145,0.007445
2026-09-18,0.025245,-0.006801,-0.014651,0.012721,-0.014069,-0.016066

In [4]:
r = returns["HDFCBANK.NS"]
position = float(1_000_000)
threshold = np.percentile(r, 0.01*100)
hist_var = (-threshold) * position
No_of_time_threshold_breached_hist = float((r < threshold).sum())
print(f"Historical VaR = {hist_var:,.4f}, No_of_time_threshold_breached_hist = {No_of_time_threshold_breached_hist:,.2f}")

Historical VaR = 38,633.7196, No_of_time_threshold_breached_hist = 20.00

In [5]:
mean = r.mean()
std_dev = r.std()
z_score = stats.norm.ppf(0.01)
threshold = mean + z_score * std_dev
para_var = (-threshold) * position
No_of_time_threshold_breached_para = float((r < threshold).sum())
print(f"Parametric VaR = {para_var:,.4f}, No_of_time_threshold_breached_para = {No_of_time_threshold_breached_para:,.2f}")

Parametric VaR = 36,098.0098, No_of_time_threshold_breached_para = 27.00

In [6]:
prices = pd.read_csv("../data/prices.csv", index_col=0, parse_dates=True)
returns = prices.pct_change().dropna()
r = returns["HDFCBANK.NS"]

threshold = r.mean() + stats.norm.ppf(0.01) * r.std()
print("Threshold (should be a small negative number):", round(threshold, 4))

hits = r[r < threshold]
print("Breaches:", len(hits))
print(hits.index.strftime("%Y-%m").value_counts().sort_index())
print("Average return on breach days:", round(hits.mean(), 4))

Threshold (should be a small negative number): -0.0361
Breaches: 27
Date
2020-03    5
2020-04    1
2020-05    3
2021-01    1
2021-02    1
2021-03    1
2021-04    2
2022-02    2
2022-03    1
2022-04    2
2023-05    1
2023-09    1
2024-01    1
2024-06    1
2024-07    1
2026-03    2
2026-07    1
Name: count, dtype: int64
Average return on breach days: -0.0561